server:
  port: 8004
spring:
  cloud:
    config:
      server:
        git:
          default-label: jwt
          uri: https://github.com/vicentemarti31416/taller-backend.git
          search-paths: config-data
          username: vicentemarti31416
          password: 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
          skip-ssl-validation: true
  application:
    name: microservicio-config

