server:
  port: ${PORT:0}
spring:
  application:
    name: microservicio-users
  cloud:
    config:
      uri: http://localhost:8004
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost