server:
  port: 8001
spring:
  application:
    name: microservicio-bikes
  cloud:
    config:
      uri: http://localhost:8004
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost